#:schema ../../schemas/json/cargo.json
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lints.rust]
unsafe_code = "forbid"
#:schema ../../schemas/json/cargo.json
